github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addComment: true
    addBadge: false
    addLabel: Gitpod Workspace Prebuild Completed

tasks:
  - name: API server
    command: vagrant up


