image: 
  file: .gitpod.Dockerfile
tasks:
  - name: streaming
    before: gp sync-await before
    init: gp sync-await init
    command: NODE_ENV=development BIND=0.0.0.0 PORT=8008 STREAMING_CLUSTER_NUM=1 node ./streaming
  - name: sidekiq
    before: |
      gp sync-await before
      redis-server --daemonize yes
    init: gp sync-await init
    command: RAILS_ENV=development DB_POOL=5 bundle exec sidekiq -c 5
  - name: web
    before: |
      mkdir -p /workspace/.rvm
      rvm install 3.0.4
      brew install --ignore-dependencies libidn redis
      gp sync-done before
    init: |
      echo "$RUBY_VERSION" | cut -d- -f2 > .ruby-version
      bundle config --local build.idn-ruby --with-idn-dir="$(brew --prefix libidn)"
      bundle install
      yarn install
      echo "LOCAL_DOMAIN=$(gp url 8080 | cut -d/ -f3)" > .env
      cat ../.env.example >> .env
      echo "SECRET_KEY_BASE=$(RAILS_ENV=development bundle exec rake secret)" >> .env
      echo "OTP_SECRET=$(RAILS_ENV=development bundle exec rake secret)" >> .env
      RAILS_ENV=development bundle exec rake mastodon:webpush:generate_vapid_key >> .env
      RAILS_ENV=development rails db:setup
      RAILS_ENV=development rails assets:precompile
      gp sync-done init
    command: RAILS_ENV=development BIND=0.0.0.0 PORT=8080 RAILS_SERVE_STATIC_FILES=true bundle exec puma -C config/puma.rb
  - name: bash
    command: |
      RAILS_ENV=development bin/tootctl accounts create dev --email "dev@local.dev" --confirmed --role Owner
      echo "E-mail address: dev@local.dev"
ports:
  - description: Web UI
    port: 8080
    visibility: public
    onOpen: open-browser
  - description: Streaming API
    port: 8008
    onOpen: ignore
  - description: postgres
    port: 5432
    onOpen: ignore
  - description: redis
    port: 6379
    onOpen: ignore
vscode:
  extensions:
    - mtxr.sqltools
    - mtxr.sqltools-driver-pg